In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import openpyxl

In [ ]:
df = pd.read_excel('Nomina.xlsx')

In [ ]:
df

,NOMBRES,FUNCION,DEPARTAMENTO,ESTATUS,SUELDO(RD$),MES,AÑO
1,JUAN ROSA,DIRECTOR GENERAL,DIRECCIÓN GENERAL,FIJO,275000,ABRIL,2025
2,PEDRO PASCUAL JIMENEZ MARTE,ASISTENTE GENERAL,DIRECCION GENERAL,FIJO,200000,ABRIL,2025
3,ELADIO ANTONIO PEGUERO MEJIA,ASISTENTE ESPECIAL,DIRECCION GENERAL,FIJO,60000,ABRIL,2025
4,RAYDEL CASTILLO SOLIS,ASISTENTE,DIRECCION GENERAL,FIJO,50000,ABRIL,2025
5,ROSA EMILIA VENTURA SANTANA,ASESOR,DIRECCION GENERAL,FIJO,170500,ABRIL,2025
...,...,...,...,...,...,...,...
401,MAXUEL ESTERLIN COLON DUARTE,AUXILIAR,DEPARTAMENTO DE AUTOSEGURO-DGJP,STATUS SIMPLIFICADO,40000,ABRIL,2025
402,FELIPE ENMANUEL RAMIREZ CASTRO,ENCARGADO,DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,FIJO,125000,ABRIL,2025
403,RAQUEL MELO D OLEO,COORDINADOR (A),DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,FIJO,60000,ABRIL,2025
404,CARMEN DELIA JIMENEZ MARTE,ANALISTA,DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,CARRERA,50000,ABRIL,2025
405,KARLA ALTAGRACIA FORTUNA VARGAS,TECNICO DE DOCUMENTACION,DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,FIJO,40000,ABRIL,2025

In [ ]:
print(df.columns)

Index(['NOMBRES', 'FUNCION', 'DEPARTAMENTO', 'ESTATUS', 'SUELDO(RD$)', 'MES',
       'AÑO'],
      dtype='object', name=0)

In [ ]:
df.to_csv('NOMINA.PENSION.csv', sep=';', index=False)

In [ ]:
df = df.drop(columns=['GENERO'])

In [ ]:
df = df.rename(columns={
    'NOMBRE Y APELLIDO': 'NOMBRES',
    'SALARIO(RD$)': 'SUELDO(RD$)',
    'CARGO': 'FUNCION',
    'CATEGORIA DEL SERVIDOR': 'ESTATUS'
})

In [ ]:
df['AÑO'] = '2025'

In [ ]:
df['AÑO'] = df['AÑO'].astype(int)

In [ ]:
df

In [ ]:
df.isnull().sum()

0
NOMBRES         0
FUNCION         0
DEPARTAMENTO    0
ESTATUS         0
SUELDO(RD$)     0
MES             0
AÑO             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 405 entries, 1 to 405
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NOMBRES       405 non-null    object
 1   FUNCION       405 non-null    object
 2   DEPARTAMENTO  405 non-null    object
 3   ESTATUS       405 non-null    object
 4   SUELDO(RD$)   405 non-null    object
 5   MES           405 non-null    object
 6   AÑO           405 non-null    int64
dtypes: int64(1), object(6)
memory usage: 41.5+ KB

In [ ]:
# Leer la hoja específica
df = pd.read_excel("Nomina.xlsx", sheet_name="NOMINA PORTAL FIJO ABRIL 2025", skiprows=12)

df.columns = df.iloc[0]  # toma esa fila y la usa como nombres de columnas
df = df[1:]              # luego elimina esa fila de los datos reales

df.head(40)

# Rellenar los valores nulos de una sola columna con 0
df['SFS SALUD ADICIONAL'] = df['SFS SALUD ADICIONAL'].fillna(0)
df.head(40)

df.info()

# Eliminar filas que están completamente vacías
df = df.dropna(how='all')

# O eliminar filas que tienen muchos NaN (por ejemplo, más de la mitad vacías)
df = df.dropna(thresh=len(df.columns)//2)

# Rellenar solo columnas numéricas con cero
columnas_numericas = ['SALARIO', 'SEGURO DE VIDA', 'IMPUESTO SOBRE LA RENTA', 'AFP', 'SEGURO FAMILIAR DE SALUD SFS', 'TOTAL DESCUENTOS', 'SUELDO NETO']
df[columnas_numericas] = df[columnas_numericas].fillna(0)

# Quitar filas donde la columna 'NO' (o la que tenga los números) diga TOTAL o esté vacía
df = df[~df['NO'].astype(str).str.upper().str.contains("TOTAL", na=False)]

# También puedes eliminar filas donde el nombre está vacío (opcional)
df = df[df['NOMBRE Y APELLIDO'].notna()]

# Rellenar con 0 en las columnas numéricas
columnas_numericas = ['SALARIO', 'SEGURO DE VIDA', 'IMPUESTO SOBRE LA RENTA', 'AFP', 'SEGURO FAMILIAR DE SALUD SFS', 'TOTAL DESCUENTOS', 'SUELDO NETO']
df[columnas_numericas] = df[columnas_numericas].fillna(0)

# Rellenar texto con "Sin dato"
df = df.fillna("Sin dato")

df.tail(10)

df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 1 to 414
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   NO                            406 non-null    object
 1   NOMBRE Y APELLIDO             405 non-null    object
 2   CARGO                         405 non-null    object
 3   DEPARTAMENTO                  406 non-null    object
 4   CATEGORIA DEL SERVIDOR        405 non-null    object
 5   GENERO                        405 non-null    object
 6   SALARIO                       408 non-null    object
 7   SEGURO DE VIDA                406 non-null    object
 8   IMPUESTO SOBRE LA RENTA       407 non-null    object
 9   AFP                           407 non-null    object
 10  SEGURO FAMILIAR DE SALUD SFS  406 non-null    object
 11  SFS SALUD ADICIONAL           414 non-null    float64
 12  TOTAL DESCUENTOS              408 non-null    object
 13  SUELDO NETO                   406 non-null    object
dtypes: float64(1), object(13)
memory usage: 45.4+ KB

<ipython-input-24-c329a007d8f3>:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['SFS SALUD ADICIONAL'] = df['SFS SALUD ADICIONAL'].fillna(0)
<ipython-input-24-c329a007d8f3>:23: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[columnas_numericas] = df[columnas_numericas].fillna(0)
<ipython-input-24-c329a007d8f3>:36: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna("Sin dato")

0
NO                              0
NOMBRE Y APELLIDO               0
CARGO                           0
DEPARTAMENTO                    0
CATEGORIA DEL SERVIDOR          0
GENERO                          0
SALARIO                         0
SEGURO DE VIDA                  0
IMPUESTO SOBRE LA RENTA         0
AFP                             0
SEGURO FAMILIAR DE SALUD SFS    0
SFS SALUD ADICIONAL             0
TOTAL DESCUENTOS                0
SUELDO NETO                     0
dtype: int64

In [ ]:
df

,NOMBRES,FUNCION,DEPARTAMENTO,ESTATUS,SUELDO(RD$),MES,AÑO
1,JUAN ROSA,DIRECTOR GENERAL,DIRECCIÓN GENERAL,FIJO,275000,ABRIL,2025
2,PEDRO PASCUAL JIMENEZ MARTE,ASISTENTE GENERAL,DIRECCION GENERAL,FIJO,200000,ABRIL,2025
3,ELADIO ANTONIO PEGUERO MEJIA,ASISTENTE ESPECIAL,DIRECCION GENERAL,FIJO,60000,ABRIL,2025
4,RAYDEL CASTILLO SOLIS,ASISTENTE,DIRECCION GENERAL,FIJO,50000,ABRIL,2025
5,ROSA EMILIA VENTURA SANTANA,ASESOR,DIRECCION GENERAL,FIJO,170500,ABRIL,2025
...,...,...,...,...,...,...,...
401,MAXUEL ESTERLIN COLON DUARTE,AUXILIAR,DEPARTAMENTO DE AUTOSEGURO-DGJP,STATUS SIMPLIFICADO,40000,ABRIL,2025
402,FELIPE ENMANUEL RAMIREZ CASTRO,ENCARGADO,DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,FIJO,125000,ABRIL,2025
403,RAQUEL MELO D OLEO,COORDINADOR (A),DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,FIJO,60000,ABRIL,2025
404,CARMEN DELIA JIMENEZ MARTE,ANALISTA,DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,CARRERA,50000,ABRIL,2025
405,KARLA ALTAGRACIA FORTUNA VARGAS,TECNICO DE DOCUMENTACION,DIVISION DE VALIDACION Y REGISTRO DE INSTRUMEN...,FIJO,40000,ABRIL,2025