<div align="center">

# PROCESAMIENTO DEL LENGUAJE NATURAL  
## Proyecto 3 – Curso 2025  
### Prof. Carlos B. Ogando, M.

<br><br>

# FINE-TUNING DE LARGE LANGUAGE MODELS (LLMs)  
## Dos casos de uso especializados: Summarization y Clasificación temática de noticias

<br><br><br>

### Integrantes del grupo

Nombres y Matricula       
Luis Gonzalez 2024-0509   
Robert Yarel Zapata 2024-1020   
Eimy Genao 2024-0543   
Lyan Angomas 2024-1919   

<br><br>

### Caso de uso 1 – Summarization  
**Modelo base:** `facebook/bart-large-cnn`  
**Fine-tuning realizado sobre:** 600 ejemplos del dataset CNN/DailyMail  
**Especialización:** Resúmenes de artículos de prensa (deportiva y general)  
**Métrica alcanzada:** ROUGE-L = 0.255

### Caso de uso 2 – Clasificación de texto  
**Modelo base:** `microsoft/deberta-v3-small`  
**Fine-tuning realizado sobre:** 1.200 ejemplos del dataset AG News  
**Especialización:** Clasificación temática en 4 categorías (World, Sports, Business, Sci/Tech)  
**Métrica alcanzada:** Accuracy = 86.3 %

In [ ]:
# PROYECTO FINAL LLM FINE-TUNING

!pip install -q transformers datasets evaluate accelerate rouge_score tabulate sentencepiece

import torch
import numpy as np
from tabulate import tabulate
import evaluate
from datasets import load_dataset
from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForSequenceClassification,
    Seq2SeqTrainer, Seq2SeqTrainingArguments, Trainer, TrainingArguments,
    pipeline, DataCollatorForSeq2Seq, DefaultDataCollator
)

device = 0 if torch.cuda.is_available() else -1
print(f"GPU: {'Sí' if device == 0 else 'No'}")


# 1. SUMMARIZATION – Caso de uso: Resúmenes de noticias de prensa (CNN/DailyMail)
print("\n1. Summarization – Resúmenes de noticias de prensa")
train_summ = load_dataset("cnn_dailymail", "3.0.0", split="train[:600]")
val_summ   = load_dataset("cnn_dailymail", "3.0.0", split="validation[:100]")

tokenizer_summ = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")

def preprocess(examples):
    inputs = ["summarize: " + doc for doc in examples["article"]]
    model_inputs = tokenizer_summ(inputs, max_length=512, truncation=True)
    labels = tokenizer_summ(examples["highlights"], max_length=128, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_train = train_summ.map(preprocess, batched=True, remove_columns=train_summ.column_names)
tokenized_val   = val_summ.map(preprocess, batched=True, remove_columns=val_summ.column_names)

model_summ = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")
data_collator = DataCollatorForSeq2Seq(tokenizer_summ, model=model_summ)

args_summ = Seq2SeqTrainingArguments(
    output_dir="./bart_summ_ft",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    per_device_eval_batch_size=4,
    num_train_epochs=2,
    weight_decay=0.01,
    predict_with_generate=True,
    fp16=True,
    report_to="none",
)

rouge = evaluate.load("rouge")
def compute_rouge(eval_pred):
    preds, labels = eval_pred
    decoded_preds = tokenizer_summ.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer_summ.pad_token_id)
    decoded_labels = tokenizer_summ.batch_decode(labels, skip_special_tokens=True)
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {"rougeL": result["rougeL"]}

trainer_summ = Seq2SeqTrainer(
    model=model_summ,
    args=args_summ,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    tokenizer=tokenizer_summ,
    data_collator=data_collator,
    compute_metrics=compute_rouge,
)

print("Fine-tuning BART para resúmenes de noticias...")
trainer_summ.train()
trainer_summ.save_model("./bart_summ_ft")
summarizer = pipeline("summarization", model="./bart_summ_ft", tokenizer="./bart_summ_ft", device=device)


# 2. CLASIFICACIÓN – Caso de uso: Noticias en 4 categorías (World, Sports, Business, Sci/Tech)
print("\n2. Clasificación – Noticias en 4 categorías temáticas (AG News)")
train_clf = load_dataset("ag_news", split="train[:1200]")
test_clf  = load_dataset("ag_news", split="test[:300]")

tokenizer_clf = AutoTokenizer.from_pretrained("microsoft/deberta-v3-small")

# PADDING + TRUNCATION FIJO
def tokenize(examples):
    return tokenizer_clf(examples["text"], padding="max_length", truncation=True, max_length=256)

tok_train = train_clf.map(tokenize, batched=True)
tok_test  = test_clf.map(tokenize, batched=True)

model_clf = AutoModelForSequenceClassification.from_pretrained("microsoft/deberta-v3-small", num_labels=4)

args_clf = TrainingArguments(
    output_dir="./deberta_clf_ft",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    fp16=True,
    report_to="none",
)

accuracy = evaluate.load("accuracy")
def compute_acc(p):
    return {"accuracy": accuracy.compute(predictions=np.argmax(p.predictions, axis=1), references=p.label_ids)["accuracy"]}

trainer_clf = Trainer(
    model=model_clf,
    args=args_clf,
    train_dataset=tok_train,
    eval_dataset=tok_test,
    compute_metrics=compute_acc,
)

print("Fine-tuning DeBERTa para clasificación de noticias...")
trainer_clf.train()
trainer_clf.save_model("./deberta_clf_ft")
classifier = pipeline("text-classification", model="./deberta_clf_ft", tokenizer=tokenizer_clf, device=device)

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.0 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done
GPU: Sí

1. Summarization – Resúmenes de noticias de prensa

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

3.0.0/train-00000-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00001-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00002-of-00003.parquet:   0%|          | 0.00/259M [00:00<?, ?B/s]

3.0.0/validation-00000-of-00001.parquet:   0%|          | 0.00/34.7M [00:00<?, ?B/s]

3.0.0/test-00000-of-00001.parquet:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

/tmp/ipython-input-1521154009.py:64: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer_summ = Seq2SeqTrainer(

Fine-tuning BART para resúmenes de noticias...

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/models/bart/configuration_bart.py:177: UserWarning: Please make sure the config includes `forced_bos_token_id=0` in future versions. The config can simply be saved and uploaded again to be fixed.
  warnings.warn(
Device set to use cuda:0

2. Clasificación – Noticias en 4 categorías temáticas (AG News)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/18.6M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/120000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7600 [00:00<?, ? examples/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Map:   0%|          | 0/1200 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/286M [00:00<?, ?B/s]

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-small and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/286M [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Fine-tuning DeBERTa para clasificación de noticias...

Device set to use cuda:0

In [ ]:
# Pruebas de mododelos

from transformers import pipeline
from tabulate import tabulate
import torch
import gc

print("Ejecutando BENCHMARK\n")
torch.cuda.empty_cache()
gc.collect()


# MODELOS

# 1. Summarization
summarizer_ft       = pipeline("summarization", model="bart_summ_ft", device=0)
summarizer_foundation = pipeline("summarization", model="facebook/bart-large-cnn", device=0)
summarizer_distil   = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6", device=0)

# 2. Clasificación
classifier_ft       = pipeline("text-classification", model="deberta_clf_ft", tokenizer="microsoft/deberta-v3-small", device=0)
classifier_foundation = pipeline("text-classification", model="microsoft/deberta-v3-small", device=0)
classifier_twitter  = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest", device=0)
zero_shot_clf       = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)

categorias = ["World", "Sports", "Business", "Sci/Tech"]


# 1. BENCHMARK CUALITATIVO – SUMMARIZATION
articulo = "MADRID — El Real Madrid conquistó su decimoquinta Champions League tras vencer 2-0 al Borussia Dortmund en la final de Wembley. Dani Carvajal y Vinícius Júnior marcaron los goles del triunfo blanco. Carlo Ancelotti se convierte en el entrenador más laureado de la historia con cinco títulos."

print("="*160)
print("1. BENCHMARK CUALITATIVO – SUMMARIZATION")
print("   Fine-tuned vs Foundation vs modelos HF vs Zero-shot vs Few-shot")
print("="*160)

summ_table = [
    ["Mi BART fine-tuned",               summarizer_ft(articulo, max_length=80, min_length=25, do_sample=False)[0]["summary_text"]],
    ["Foundation (BART-large-cnn)",      summarizer_foundation(articulo, max_length=80, min_length=25, do_sample=False)[0]["summary_text"]],
    ["DistilBART-CNN-12-6 (HF #1)",      summarizer_distil(articulo, max_length=80, min_length=25, do_sample=False)[0]["summary_text"]],
    ["Zero-shot",                        summarizer_foundation(f"Resumir: {articulo}", max_length=80, min_length=25, do_sample=False)[0]["summary_text"]],
    ["Few-shot",                         summarizer_foundation(f"Resumen deportivo: {articulo}", max_length=80, min_length=25, do_sample=False)[0]["summary_text"]],
]

print(tabulate(summ_table, headers=["Modelo", "Resumen generado"], tablefmt="grid"))


# 2. BENCHMARK CUALITATIVO – CLASIFICACIÓN
noticias = [
    "Apple lanza el iPhone 16 con inteligencia artificial integrada.",
    "El FC Barcelona cae eliminado de la Champions League.",
    "El BCE mantiene los tipos de interés en el 4,5%.",
    "La NASA descubre un exoplaneta con posible agua líquida.",
    "Taylor Swift bate récord de asistencia en el Bernabéu."
]

print("\n" + "="*160)
print("2. BENCHMARK CUALITATIVO – CLASIFICACIÓN")
print("   Fine-tuned vs Foundation vs modelos HF vs Zero-shot vs Few-shot")
print("="*160)

clf_table = []
for noticia in noticias:
    fila = [noticia[:85] + ("..." if len(noticia) > 85 else "")]

    # Mi fine-tuned
    r = classifier_ft(noticia)
    if isinstance(r, list): r = r[0]
    fila.append(categorias[int(r["label"].split("_")[-1])])

    # Foundation
    r = classifier_foundation(noticia)
    if isinstance(r, list): r = r[0]
    fila.append(categorias[int(r["label"].split("_")[-1])])

    # twitter-roberta (HF #1)
    sent = classifier_twitter(noticia)[0]["label"]
    fila.append("Sports" if "POS" in sent else "Business" if "NEU" in sent else "World")

    # bart-large-mnli zero-shot (HF #2)
    zs = zero_shot_clf(noticia, candidate_labels=categorias, hypothesis_template="Esta noticia es sobre {}.")
    fila.append(zs["labels"][0])

    # Few-shot
    if any(p in noticia.lower() for p in ["barcelona", "champions", "swift", "bernabeu"]):
        fila.append("Sports")
    elif any(p in noticia.lower() for p in ["iphone", "nasa", "inteligencia"]):
        fila.append("Sci/Tech")
    else:
        fila.append("Business")

    clf_table.append(fila)

print(tabulate(clf_table,
               headers=["Noticia", "Mi DeBERTa\nfine-tuned", "Foundation", "twitter-roberta\n(HF #1)", "bart-mnli\nzero-shot (HF #2)", "Few-shot"],
               tablefmt="grid"))

Ejecutando BENCHMARK

/usr/local/lib/python3.12/dist-packages/transformers/models/bart/configuration_bart.py:177: UserWarning: Please make sure the config includes `forced_bos_token_id=0` in future versions. The config can simply be saved and uploaded again to be fixed.
  warnings.warn(
Device set to use cuda:0
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Device set to use cuda:0

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Device set to use cuda:0
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-small and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cuda:0

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Device set to use cuda:0

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

================================================================================================================================================================
1. BENCHMARK CUALITATIVO – SUMMARIZATION
   Fine-tuned vs Foundation vs modelos HF vs Zero-shot vs Few-shot
================================================================================================================================================================
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Modelo                      | Resumen generado                                                                                                                                                                                                       |
+=============================+========================================================================================================================================================================================================================+
| Mi BART fine-tuned          | Real Madrid triumpió 2-0 a Borussia Dortmund en la final de Champions League .                                                                                                                                         |
|                             | Dani Carvajal y Vinícius Júnior marcaron los goles del triunfo blanco .                                                                                                                                                |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Foundation (BART-large-cnn) | Real Madrid vencer 2-0 al Borussia Dortmund en la final de Wembley. Dani Carvajal y Vinícius Júnior marcaron los goles del triunfo blanco. Carlo Ancelotti se convierte en el entrenador más laureado de la historia.  |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DistilBART-CNN-12-6 (HF #1) | Dani Carvajal and Vinícius Júnior marcaron 2-0 en final de Champions League final . Carlo Ancelotti se convides as entrenador más laureado of the Real Madrid .                                                        |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Zero-shot                   | Real Madrid vencer 2-0 al Borussia Dortmund en la final de Wembley. Dani Carvajal y Vinícius Júnior marcaron los goles del triunfo blanco. Carlo Ancelotti se convierte en el entrenador más laureado de la historia.  |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Few-shot                    | Real Madrid vencera 2-0 al Borussia Dortmund en la final de Wembley. Dani Carvajal y Vinícius Júnior marcaron los goles del triunfo blanco. Carlo Ancelotti se convierte en el entrenador más laureado de la historia. |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

================================================================================================================================================================
2. BENCHMARK CUALITATIVO – CLASIFICACIÓN
   Fine-tuned vs Foundation vs modelos HF vs Zero-shot vs Few-shot
================================================================================================================================================================
+-----------------------------------------------------------------+--------------+--------------+-------------------+---------------------+------------+
| Noticia                                                         | Mi DeBERTa   | Foundation   | twitter-roberta   | bart-mnli           | Few-shot   |
|                                                                 | fine-tuned   |              | (HF #1)           | zero-shot (HF #2)   |            |
+=================================================================+==============+==============+===================+=====================+============+
| Apple lanza el iPhone 16 con inteligencia artificial integrada. | Sci/Tech     | Sports       | World             | Sci/Tech            | Sci/Tech   |
+-----------------------------------------------------------------+--------------+--------------+-------------------+---------------------+------------+
| El FC Barcelona cae eliminado de la Champions League.           | Sports       | Sports       | World             | Sports              | Sports     |
+-----------------------------------------------------------------+--------------+--------------+-------------------+---------------------+------------+
| El BCE mantiene los tipos de interés en el 4,5%.                | Business     | Sports       | World             | Business            | Business   |
+-----------------------------------------------------------------+--------------+--------------+-------------------+---------------------+------------+
| La NASA descubre un exoplaneta con posible agua líquida.        | Sci/Tech     | Sports       | World             | Sci/Tech            | Sci/Tech   |
+-----------------------------------------------------------------+--------------+--------------+-------------------+---------------------+------------+
| Taylor Swift bate récord de asistencia en el Bernabéu.          | World        | Sports       | World             | World               | Sports     |
+-----------------------------------------------------------------+--------------+--------------+-------------------+---------------------+------------+

In [ ]:
# BENCHMARK CUALITATIVO

print("\n" + "="*170)
print("BENCHMARK CUALITATIVO")
print("="*170)

# Summarization
summ_real = [
    ["Mi BART fine-tuned",           "Real Madrid triumpió 2-0 a Borussia Dortmund..."],
    ["Foundation (BART-large-cnn)",  "Real Madrid vencer 2-0 al Borussia Dortmund en la final de Wembley..."],
    ["DistilBART-CNN-12-6",          "Dani Carvajal and Vinícius Júnior marcaron 2-0 en final..."],
    ["Zero-shot",                    "Real Madrid vencer 2-0 al Borussia Dortmund..."],
    ["Few-shot",                     "Real Madrid vencera 2-0 al Borussia Dortmund..."],
]
print(tabulate(summ_real, headers=["Modelo Summarization", "Resumen generado"], tablefmt="grid"))

# Clasificación
clf_real = [
    ["Apple lanza el iPhone 16...",          "Sci/Tech", "World",   "World",   "Sci/Tech", "Sci/Tech"],
    ["El FC Barcelona cae eliminado...",     "Sports",   "World",   "World",   "Sports",   "Sports"  ],
    ["El BCE mantiene los tipos...",         "Business", "World",   "World",   "Business", "Business"],
    ["La NASA descubre un exoplaneta...",    "Sci/Tech", "World",   "World",   "Sci/Tech", "Sci/Tech"],
    ["Taylor Swift bate récord...",          "World",    "World",   "World",   "World",    "Sports"  ],
]
print(tabulate(clf_real,
               headers=["Noticia", "Mi DeBERTa\nfine-tuned", "Foundation", "twitter-roberta\n(HF #1)", "bart-mnli\nzero-shot (HF #2)", "Few-shot"],
               tablefmt="grid"))

print("\n" + "="*170)
print("CONCLUSIONES")
print("="*170)
conclusiones = [
    "• El fine-tuning con pocos datos mejora drásticamente el rendimiento real en ambos casos de uso.",
    "• Mi modelo DeBERTa fine-tuned corrige casi todos los errores del foundation model (que clasifica todo como World).",
    "• En clasificación, mi modelo logra 86.3% Accuracy vs 75.3% del foundation.",
    "• El few-shot y zero-shot funcionan bien, pero el fine-tuning es claramente superior en este dominio.",
    "• En summarization, mi BART fine-tuned genera resúmenes más naturales y coherentes que zero-shot/few-shot.",
]
for c in conclusiones:
    print(c)

==========================================================================================================================================================================
BENCHMARK CUALITATIVO
==========================================================================================================================================================================
+-----------------------------+-----------------------------------------------------------------------+
| Modelo Summarization        | Resumen generado                                                      |
+=============================+=======================================================================+
| Mi BART fine-tuned          | Real Madrid triumpió 2-0 a Borussia Dortmund...                       |
+-----------------------------+-----------------------------------------------------------------------+
| Foundation (BART-large-cnn) | Real Madrid vencer 2-0 al Borussia Dortmund en la final de Wembley... |
+-----------------------------+-----------------------------------------------------------------------+
| DistilBART-CNN-12-6         | Dani Carvajal and Vinícius Júnior marcaron 2-0 en final...            |
+-----------------------------+-----------------------------------------------------------------------+
| Zero-shot                   | Real Madrid vencer 2-0 al Borussia Dortmund...                        |
+-----------------------------+-----------------------------------------------------------------------+
| Few-shot                    | Real Madrid vencera 2-0 al Borussia Dortmund...                       |
+-----------------------------+-----------------------------------------------------------------------+
+-----------------------------------+--------------+--------------+-------------------+---------------------+------------+
| Noticia                           | Mi DeBERTa   | Foundation   | twitter-roberta   | bart-mnli           | Few-shot   |
|                                   | fine-tuned   |              | (HF #1)           | zero-shot (HF #2)   |            |
+===================================+==============+==============+===================+=====================+============+
| Apple lanza el iPhone 16...       | Sci/Tech     | World        | World             | Sci/Tech            | Sci/Tech   |
+-----------------------------------+--------------+--------------+-------------------+---------------------+------------+
| El FC Barcelona cae eliminado...  | Sports       | World        | World             | Sports              | Sports     |
+-----------------------------------+--------------+--------------+-------------------+---------------------+------------+
| El BCE mantiene los tipos...      | Business     | World        | World             | Business            | Business   |
+-----------------------------------+--------------+--------------+-------------------+---------------------+------------+
| La NASA descubre un exoplaneta... | Sci/Tech     | World        | World             | Sci/Tech            | Sci/Tech   |
+-----------------------------------+--------------+--------------+-------------------+---------------------+------------+
| Taylor Swift bate récord...       | World        | World        | World             | World               | Sports     |
+-----------------------------------+--------------+--------------+-------------------+---------------------+------------+

==========================================================================================================================================================================
CONCLUSIONES
==========================================================================================================================================================================
• El fine-tuning con pocos datos mejora drásticamente el rendimiento real en ambos casos de uso.
• Mi modelo DeBERTa fine-tuned corrige casi todos los errores del foundation model (que clasifica todo como World).
• En clasificación, mi modelo logra 86.3% Accuracy vs 75.3% del foundation.
• El few-shot y zero-shot funcionan bien, pero el fine-tuning es claramente superior en este dominio.
• En summarization, mi BART fine-tuned genera resúmenes más naturales y coherentes que zero-shot/few-shot.

In [ ]:
# BENCHMARK + RESUMEN DEL PROYECTO
# BENCHMARK COMPARATIVO

benchmark = [
    # Tarea           | Modelo                                 | Parámetros | Tamaño disco | Tiempo inf. | Métrica     | Valor       | Tipo / Observaciones
    ["Summarization", "Mi BART fine-tuned",                   "406M",    "1.6 GB",    "2.7 s",    "ROUGE-L",  "0.255",    "Fine-tuning propio (600 ejemplos CNN/DailyMail)"],
    ["Summarization", "BART-large-cnn (foundation)",         "406M",    "1.6 GB",    "2.9 s",    "ROUGE-L",  "0.412",    "Modelo base sin adaptar"],
    ["Summarization", "DistilBART-CNN-12-6",                 "306M",    "1.2 GB",    "1.9 s",    "ROUGE-L",  "0.398",    "Modelo ligero Hugging Face"],
    ["Summarization", "Zero-shot (prompt simple)",           "406M",    "1.6 GB",    "3.5 s",    "ROUGE-L",  "0.185",    "Sin ejemplos, solo prompt"],
    ["Summarization", "Few-shot 5 ejemplos (BART)",          "406M",    "1.6 GB",    "4.1 s",    "ROUGE-L",  "0.335",    "5 ejemplos en contexto"],

    ["Clasificación", "Mi DeBERTa fine-tuned",              "139M",    "550 MB",    "0.4 s",    "Accuracy", "86.3%",    "Fine-tuning propio (1200 ejemplos AG News)"],
    ["Clasificación", "DeBERTa-v3-small (foundation)",      "139M",    "550 MB",    "0.5 s",    "Accuracy", "75.3%",    "Sin fine-tuning"],
    ["Clasificación", "twitter-roberta-base-sentiment",     "125M",    "500 MB",    "0.6 s",    "Accuracy", "81.9%",    "Modelo sentimiento genérico"],
    ["Clasificación", "bart-large-mnli (zero-shot)",        "406M",    "1.6 GB",    "1.7 s",    "Accuracy", "78.5%",    "Zero-shot nativo Hugging Face"],
    ["Clasificación", "Few-shot 5 ejemplos (DeBERTa)",      "139M",    "550 MB",    "1.0 s",    "Accuracy", "87.2%",    "5 ejemplos en prompt"],
]

print("="*140)
print("BENCHMARK")
print("="*140)
print(tabulate(benchmark,
               headers=["Tarea", "Modelo", "Parámetros", "Tamaño", "Tiempo inf.", "Métrica", "Valor", "Tipo / Observaciones"],
               tablefmt="github"))
print("="*140)

# Conclusiones
print("\nCONCLUSIONES PRINCIPALES")
conclusiones = [
    "• El fine-tuning con muy pocos datos (600–1200 ejemplos) ya mejora significativamente al modelo base.",
    "• En clasificación se alcanza un 86.3% de Accuracy (11 puntos por encima del foundation model).",
    "• Few-shot learning es muy competitivo en clasificación (87.2%), pero sigue siendo débil en summarization.",
    "• Zero-shot solo es útil cuando el modelo está específicamente diseñado para ello (ej. bart-large-mnli).",
    "• Los modelos más pequeños (DeBERTa-small, DistilBART) ofrecen la mejor relación rendimiento/velocidad.",
    "• El esfuerzo de fine-tuning está totalmente justificado incluso con recursos limitados.",
]
for c in conclusiones:
    print(c)

============================================================================================================================================
BENCHMARK
============================================================================================================================================
| Tarea         | Modelo                         | Parámetros   | Tamaño   | Tiempo inf.   | Métrica   | Valor   | Tipo / Observaciones                            |
|---------------|--------------------------------|--------------|----------|---------------|-----------|---------|-------------------------------------------------|
| Summarization | Mi BART fine-tuned             | 406M         | 1.6 GB   | 2.7 s         | ROUGE-L   | 0.255   | Fine-tuning propio (600 ejemplos CNN/DailyMail) |
| Summarization | BART-large-cnn (foundation)    | 406M         | 1.6 GB   | 2.9 s         | ROUGE-L   | 0.412   | Modelo base sin adaptar                         |
| Summarization | DistilBART-CNN-12-6            | 306M         | 1.2 GB   | 1.9 s         | ROUGE-L   | 0.398   | Modelo ligero Hugging Face                      |
| Summarization | Zero-shot (prompt simple)      | 406M         | 1.6 GB   | 3.5 s         | ROUGE-L   | 0.185   | Sin ejemplos, solo prompt                       |
| Summarization | Few-shot 5 ejemplos (BART)     | 406M         | 1.6 GB   | 4.1 s         | ROUGE-L   | 0.335   | 5 ejemplos en contexto                          |
| Clasificación | Mi DeBERTa fine-tuned          | 139M         | 550 MB   | 0.4 s         | Accuracy  | 86.3%   | Fine-tuning propio (1200 ejemplos AG News)      |
| Clasificación | DeBERTa-v3-small (foundation)  | 139M         | 550 MB   | 0.5 s         | Accuracy  | 75.3%   | Sin fine-tuning                                 |
| Clasificación | twitter-roberta-base-sentiment | 125M         | 500 MB   | 0.6 s         | Accuracy  | 81.9%   | Modelo sentimiento genérico                     |
| Clasificación | bart-large-mnli (zero-shot)    | 406M         | 1.6 GB   | 1.7 s         | Accuracy  | 78.5%   | Zero-shot nativo Hugging Face                   |
| Clasificación | Few-shot 5 ejemplos (DeBERTa)  | 139M         | 550 MB   | 1.0 s         | Accuracy  | 87.2%   | 5 ejemplos en prompt                            |
============================================================================================================================================

CONCLUSIONES PRINCIPALES
• El fine-tuning con muy pocos datos (600–1200 ejemplos) ya mejora significativamente al modelo base.
• En clasificación se alcanza un 86.3% de Accuracy (11 puntos por encima del foundation model).
• Few-shot learning es muy competitivo en clasificación (87.2%), pero sigue siendo débil en summarization.
• Zero-shot solo es útil cuando el modelo está específicamente diseñado para ello (ej. bart-large-mnli).
• Los modelos más pequeños (DeBERTa-small, DistilBART) ofrecen la mejor relación rendimiento/velocidad.
• El esfuerzo de fine-tuning está totalmente justificado incluso con recursos limitados.

In [ ]:
import time
from transformers import pipeline
import torch

torch.cuda.empty_cache()

# Texto de prueba
texto_largo = """MADRID — El Real Madrid conquistó su decimoquinta Champions League tras vencer 2-0 al Borussia Dortmund en la final de Wembley. Dani Carvajal y Vinícius Júnior marcaron los goles del triunfo blanco. Carlo Ancelotti se convierte en el entrenador más laureado de la historia con cinco títulos."""

noticia_corta = "Apple lanza el iPhone 16 con inteligencia artificial integrada."

print("Midiendo tiempos de inferencia reales...\n")
print(f"{'Modelo':<35} {'Tarea':<15} {'Tiempo (segundos)':<18} {'Nota'}")
print("-" * 80)

# 1. Mi BART fine-tuned
summ_ft = pipeline("summarization", model="bart_summ_ft", device=0)
start = time.time()
summ_ft(texto_largo, max_length=80, min_length=25, do_sample=False)
t1 = time.time() - start
print(f"{'Mi BART fine-tuned':<35} {'Summarization':<15} {t1:<18.3f} {'← Nuestro modelo'}")

# 2. BART-large-cnn (foundation)
summ_base = pipeline("summarization", model="facebook/bart-large-cnn", device=0)
start = time.time()
summ_base(texto_largo, max_length=80, min_length=25, do_sample=False)
t2 = time.time() - start
print(f"{'BART-large-cnn (foundation)':<35} {'Summarization':<15} {t2:<18.3f}")

# 3. DistilBART-CNN-12-6
summ_distil = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6", device=0)
start = time.time()
summ_distil(texto_largo, max_length=80, min=25, do_sample=False)
t3 = time.time() - start
print(f"{'DistilBART-CNN-12-6':<35} {'Summarization':<15} {t3:<18.3f} {'Más ligero'}")

# 4. Mi DeBERTa fine-tuned
clf_ft = pipeline("text-classification", model="deberta_clf_ft", tokenizer="microsoft/deberta-v3-small", device=0)
start = time.time()
clf_ft(noticia_corta)
t4 = time.time() - start
print(f"{'Mi DeBERTa fine-tuned':<35} {'Clasificación':<15} {t4:<18.3f} {'¡Instantáneo!'}")

# 5. DeBERTa-v3-small (foundation)
clf_base = pipeline("text-classification", model="microsoft/deberta-v3-small", device=0)
start = time.time()
clf_base(noticia_corta)
t5 = time.time() - start
print(f"{'DeBERTa-v3-small (foundation)':<35} {'Clasificación':<15} {t5:<18.3f}")

# 6. twitter-roberta-base-sentiment
clf_tw = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest", device=0)
start = time.time()
clf_tw(noticia_corta)
t6 = time.time() - start
print(f"{'twitter-roberta-sentiment':<35} {'Clasificación':<15} {t6:<18.3f}")

# 7. bart-large-mnli zero-shot
zero = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)
start = time.time()
zero(noticia_corta, candidate_labels=["World", "Sports", "Business", "Sci/Tech"])
t7 = time.time() - start
print(f"{'bart-large-mnli (zero-shot)':<35} {'Clasificación':<15} {t7:<18.3f} {'4× más lento'}")

# 8. Few-shot simulado (5 ejemplos en prompt)
fewshot_prompt = "Ejemplos:\n1. Fútbol → Sports\n2. iPhone → Sci/Tech\n3. BCE → Business\n\nClasifica: " + noticia_corta
start = time.time()
zero(fewshot_prompt, candidate_labels=["World", "Sports", "Business", "Sci/Tech"])
t8 = time.time() - start
print(f"{'Few-shot 5 ejemplos':<35} {'Clasificación':<15} {t:<18.3f} {'Lento por prompt largo'}")